name: user_account
description: User account SDK for TIKI
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  httpp:
    git: https://github.com/tiki/httpp
  provider: ^6.0.2
  logging: ^1.0.2
  package_info: ^2.0.2
  share_plus: ^3.1.0
  qr_flutter: ^4.0.0
  zendesk_flutter:
    git:
      url: https://github.com/tiki/zendesk_flutter
      ref: 0.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mytiki.user_account
        pluginClass: UserAccountPlugin
      ios:
        pluginClass: UserAccountPlugin
  assets:
    - res/images/