name: tiki_user_account
description: User account SDK for TIKI
version: 0.0.9
homepage: https://mytiki.com
repository: https://github.com/tiki/user_account
issue_tracker: https://github.com/tiki/user_account/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  httpp: ^0.0.4
  provider: ^6.0.2
  logging: ^1.0.2
  package_info: ^2.0.2
  flutter_secure_storage: ^5.0.2
  share_plus: ^3.1.0
  qr_flutter: ^4.0.0
  tiki_style: ^0.0.17
  zendesk_flutter: ^0.0.6
  tiki_upvoty: ^0.0.14
  url_launcher: ^6.1.0
  sqflite_sqlcipher: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0